### ISSUE TITLE
Bring referral-unlock forward in the app, and simplify the scheme

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#79]
Bring referral unlock forward. Basically, we want to present an empty app until they unlock it by entering a referral. Referrals need to be simple. It needs to be a unique identifier for threefold people. Could be their itsyou.online email account, or the first four characters of their name.

Behind the scenes, allow this unique identifier to be changed to something else, such as a four-letter code. It will be up to threefold people to communicate their UID to the people who they invite.

**Comment by despiegk** [comment]
- first four characters will be too simple I think, you can hash and then use 4 letters (maybe 5)

**Comment by dvorkbod** [comment]
OK, so first functionality for unregistered people is:
Wallet
Chat
Link to website
Add friends
Register (requires unlock code)

**Comment by dvorkbod** [comment]
This unlock code makes wallet, hoster and ito functionality visible.

**Comment by dvorkbod** [comment]
![photo5872957500985289542](https://user-images.githubusercontent.com/26708761/30120278-ac21b1ae-9328-11e7-93cf-dce41a34d6f6.jpg)
About button needs to be populated with info blurb and link to website.
Call should get replaced with "register" - but that is programatically not possible.
Next to ask a question, we have "Add friends" - on the basis of phone numbers that are TF app and IYO registered.
Next, we have "Chat with friends"
Next to that, "Wallet"
Next row: "Become a hoster", "become an investor", "check node transit" and then the current "notification settings".

This will be split up in separate issues if required.

**Comment by dvorkbod** [comment]
Actually, the "register" button has to be used only once, so after people have registered, this button should become the "become an investor" button and flow.

**Comment by FastGeert** [comment]
@dvorkbod @despiegk Can you please describe the problem instead of coming up with solutions. What you guys ask would mean that we need to custom, which means a lot of work. 

If we understand the problem we can suggest the best way to solve it with the least amount of work.

**Comment by bart-at-mobicage** [comment]
@despiegk, which are the core problems you want to solve? I see a lot of proposed solutions, which can be custom built into the TF service. IMO, it would be better if we enrich the Rogerthat framework and build the features in there.

Some problems that I think you want to solve:

### Add friends
- If it is not clear enough how friends can be added, then I suggest we show a nice explanation when you have no friends yet. Just like we do when a service list is empty.
<img src="https://user-images.githubusercontent.com/17762105/30154883-8a670bfc-93bb-11e7-9cc6-1648dd9f9e95.PNG" width="200px">
- If you want to find friend using IYO phone numbers, then I suggest we add a phone number field to the `UserProfile` in rogerthat. This field (and also name and avatar) could be populated by the TF service at the time the user registers, because the TF service get's it from IYO.

### Chat with friends
-  If it is not clear enough how to start a chat, then I suggest then we can show a nice explanation when the message list is empty. If you would start a chat and you don't have friends yet, then we can explain the user how to find friends (and send him to the "Add friends" page).

### Invitation codes
- IMO, invitation codes would make it more complex than just selecting your referral as a friend. But no problem, we can build this. This means that everyone in the `threefold.users.invited` IYO sub-org will need to have a "My invitation code" button, to show his 4/5-letter invitation code. This also mean that we need to add everyone else to the `threefold.users.not-invited` group.

### Add friends / Chat with friends / Wallet buttons in the TF service
- If you want these 3 buttons in the TF service, we can add them. However, these 3 can already be found in the sidebar and if we include the features mentioned above, maybe it's not needed anymore to add them in the TF service.
- We will add a feature to the rogerthat framework to sort the menu items, such that there are no "gaps" anymore. We will also increase the max amount of rows from 3 to 4 (because screen sizes are increased over the years). 

- This would result in the following views
  - With all requested buttons

##### threefold.users.public

| | | | |
|-|-|-|-|
| About | History  | Recommend | Register |
| Chat with friends | Add friends | Notification settings |  | 

##### threefold.users.invited

| | | | |
|-|-|-|-|
| About | History  | Recommend | Chat with friends |
| Add friends | Become a hoster | Become an investor | Wallet | 
| Notification settings | | | | 

##### threefold.users.hoster

| | | | |
|-|-|-|-|
| About | History  | Recommend | Chat with friends |
| Add friends | Become a hoster | Check node transit | Become an investor |
| Wallet | Notification settings | | |
